Repository Jellyfish-Insights/andromeda, pull requests merged in 2020-01, with the labels that each got.

#13 Add Continuous Integration
  .github/workflows/dotnetcore.yml
  ci.sh
  src/Test/FacebookFetcherTest.cs
  src/Test/FacebookTransformationTest.cs
Labels: :chart_with_upwards_trend: enhancement

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report---.md
Labels: 📖 documentation

#27 Remove frontend tests from CI
  ci.sh
  src/ap.sln
  src/src.sln
Labels: :chart_with_upwards_trend: enhancement

#22 Add PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: :chart_with_upwards_trend: enhancement, 📖 documentation

#28 Fix discrepancy on Facebook data
  src/ConsoleApp/schema/page_3.3.json
Labels: 🐛 bug

#38 Fix some typos
  src/ConsoleApp/Commands/RunJobsCommand.cs
  src/Jobs.Fetcher.Facebook/Client/ApiManager.cs
  src/Jobs.Fetcher.Facebook/Client/Fetcher.cs
Labels: 📖 documentation
